# Main
title:            ZennoExtensions
tagline:          'A Jekyll theme'
description:      'Библиотека для <a href="http://zennolab.com/ru/products/zennoposter/" target="_blank">ZennoPoster</a>'
url:              "https://github.com/ZennoDev/ZennoExtensions.Site"
baseurl:          ""

# Settings
markdown:         kramdown
highlighter:      rouge
future:           false
permalink:        /:categories/:title/
#paginate:         5
#paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
                  - jekyll-feed

# Sidebar
sidebar_start_link:   '/start'
sidebar_docs_link:    '/docs'