# Main
title:            ZennoExtensions
description:      'Библиотека для <a href="http://zennolab.com/ru/products/zennoposter/" target="_blank">ZennoPoster</a>'
url:              "https://zennodev.github.io/ZennoExtensions.Site/"
baseurl:          "https://zennodev.github.io/ZennoExtensions.Site/"

# Settings
markdown:         kramdown
highlighter:      rouge

plugins:
                  - jekyll-feed

# Sidebar
sidebar_start_link:   '/start'
sidebar_docs_link:    '/docs'
